### ISSUE TITLE
Research deployment environment to use

### ISSUE THREAD

**Issue by NunoDasNeves** [SmartCourse/app#145]
Need a production/dev server where we can easily deploy the app and retain existing data (e.g. separate database server).
Deploying the node app in a container might be the easiest way, but just having a linux instance would work fine too.

Possible candidates:
AWS
Azure
DigitalOcean
Heroku

Heroku looks pretty good actually, and has a free tier that might suit us well.

**Comment by PapaPwn** [comment]
Initially considered using AWS or Azure since we already have credits for these and so if we wanted to do scaling we would not have to go out of pocket (which would be the case for Heroku). Played around with AWS first since I had the most experience with it, but wasn't able to use it very easily (probably just me), but found azure much simpler. Therefore, decided we will be using Azure.
